apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
spec:
  rules:
  - host: cloudempowered.co
    http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 5000
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 5001            