apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapersist-pvc
  namespace: default
  labels:
    app: datapersist-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - debug
