name: Build Images and Deploy in ECR
on:
  push:
    branches:
      - "main"
env:
  AWS_REGION : "us-east-1"
  ENV: "prod"

jobs:
  integration:
    name: create application images from source code
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code from GitHub to runner
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::376117310197:role/oidc_identity
          role-duration-seconds: 1200
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voting-app
          IMAGE_TAG_VOTE: vote-${{ env.ENV }}-${{ github.sha }}
          IMAGE_TAG_RESULT: result-${{ env.ENV }}-${{ github.sha }}
          IMAGE_TAG_WORKER: worker-${{ env.ENV }}-${{ github.sha }}
        # Build docker images for vote, result and worker modules and push them to ECR so that it can be deployed to EKS.
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_VOTE --build-arg aws_region=${{ env.AWS_REGION }} --build-arg in_aws="yes" --build-arg copy_or_mount="copy" -f vote/Dockerfile ./vote
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_VOTE
          echo "::set-output vote=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_VOTE"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_RESULT --build-arg aws_region=${{ env.AWS_REGION }} --build-arg in_aws="yes" --build-arg copy_or_mount="copy" -f result/Dockerfile ./result
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_RESULT
          echo "::set-output result=image::$ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_RESULT"     
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_WORKER --build-arg aws_region=${{ env.AWS_REGION }} --build-arg in_aws="yes" --build-arg copy_or_mount="copy" -f worker/Dockerfile ./worker
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_WORKER
          echo "::set-output worker=image::$ECR_REGISTRY/$ECR_REPOSITORY:$$IMAGE_TAG_WORKER"
                              